steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: '/'
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['test']
#   dir: '/'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'testing-cicd', '--trigger-http ', '--runtime', 'nodejs16', '--entry-point', 'helloHttp']
  dir: '/'