steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'testing-cloudbuild', '--trigger-http', '--runtime', 'nodejs16', '--entry-point', 'helloHttp','--region','asia-southeast2','--ingress-settings','internal-only','--vpc-connector','cf-connect','--egress-settings','private-ranges-only','--memory','128MB']
